language: python
python:
- '3.3'
- '3.4'
- '3.5'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- py.test tests/ --cov inet --cov-report term-missing
after_success:
- coveralls
